name: ml-tree
channels:
  - defaults
  - conda-forge
dependencies:
  - lightgbm=4.1.0
  - matplotlib=3.8.0
  - notebook=7.0.6
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.3
  - python=3.11.5
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - sktime=0.25.0
  - statsmodels=0.14.0
  - graphviz
  - python-graphviz
  - pydotplus
  - pip:
      - pmdarima==2.0.4
